Repository CesiumGS/cesium, pull requests merged in 2019-05, with the labels that each got.

#7796 Model caching fix
  CHANGES.md
  Source/Scene/Model.js
Labels: priority - next release

#7807 Test code cleanup.
  Specs/Core/CesiumTerrainProviderSpec.js
  Specs/Core/ColorSpec.js
  Specs/Core/EllipsoidSpec.js
  Specs/Core/GoogleEarthEnterpriseTerrainProviderSpec.js
  Specs/Core/GroundPolylineGeometrySpec.js
  Specs/Core/HeapSpec.js
  Specs/Core/ResourceSpec.js
  Specs/Core/SphericalSpec.js
  Specs/Core/VRTheWorldTerrainProviderSpec.js
  Specs/Core/VertexFormatSpec.js
  Specs/Core/loadCRNSpec.js
  Specs/Core/loadKTXSpec.js
  Specs/DataSources/CzmlDataSourceSpec.js
  Specs/DataSources/PointVisualizerSpec.js
  Specs/DataSources/PolylineGeometryUpdaterSpec.js
  Specs/Renderer/ContextSpec.js
  Specs/Scene/ArcGisMapServerImageryProviderSpec.js
  Specs/Scene/CameraSpec.js
  Specs/Scene/Cesium3DTilesetSpec.js
  Specs/Scene/GroundPolylinePrimitiveSpec.js
  Specs/Widgets/ProjectionPicker/ProjectionPickerViewModelSpec.js
  Specs/addDefaultMatchers.js
Labels: cleanup

#7812 Fix PostProcessStageTextureCache.clear, which previously didn't clear anything.
  Source/Scene/PostProcessStageTextureCache.js
Labels: type - bug

#7839 Don't send ion access token to non-ion servers
  CHANGES.md
  Source/Core/IonResource.js
  Specs/Core/IonResourceSpec.js
Labels: priority - next release

#7851 Check childTileMask if provider doesn't know tile availability.
  CHANGES.md
  Source/Scene/GlobeSurfaceTile.js
Labels: priority - next release

#7848 Reduce Bing Maps transactions and ion Bing sessions
  CHANGES.md
  Source/Scene/BingMapsImageryProvider.js
  Source/Scene/IonImageryProvider.js
  Specs/Scene/BingMapsImageryProviderSpec.js
  Specs/Scene/IonImageryProviderSpec.js
Labels: priority - next release

#7857 Fixed shader error in old versions of ANGLE
  Source/Shaders/GroundAtmosphere.glsl
Labels: priority - next release

#7854 TerrainOffsetProperty was not being cleaned up
  CHANGES.md
  Source/DataSources/GeometryVisualizer.js
  Source/DataSources/GroundGeometryUpdater.js
  Specs/DataSources/GeometryVisualizerSpec.js
  Specs/DataSources/GroundGeometryUpdaterSpec.js
Labels: priority - next release

#7861 Don't rewrite Bing tile URLs to https, instead just ask for https
  Source/Scene/BingMapsImageryProvider.js
Labels: priority - next release

#7878 Fix credits for request render mode
  Source/Scene/Cesium3DTileset.js
  Source/Scene/Scene.js
Labels: priority - next release
