Repository CesiumGS/cesium, pull requests merged in 2020-06, with the labels that each got.

#8936 Only include Source folder in TypeScript smokescreen tests.
  Specs/TypeScript/tsconfig.json
Labels: category - typescript

#8923 Expose buildModuleUrl as part of the Cesium API
  CHANGES.md
  Source/Core/buildModuleUrl.js
Labels: category - doc, category - typescript

#8941 Fix geometry creation in TypeScript
  CHANGES.md
  Source/Core/GeometryFactory.js
  Source/Core/GeometryInstance.js
  Source/Core/PlaneGeometry.js
  Source/Core/SimplePolylineGeometry.js
  Source/Core/SphereGeometry.js
  Source/Core/SphereOutlineGeometry.js
  Specs/TypeScript/index.ts
  Specs/TypeScript/tsconfig.json
Labels: category - typescript

#9002 Fixes ScreenSpaceEventHandler.getInputAction JSDoc
  CHANGES.md
  Source/Core/ScreenSpaceEventHandler.js
Labels: priority - next release

#8993 Avoid 'use' in SVG due to iOS 13.5.1 bug
  CHANGES.md
  Source/Widgets/Animation/Animation.js
Labels: priority - next release

#9005 Destroy scene in specs
  Specs/Scene/SceneSpec.js
Labels: priority - next release
