Repository CesiumGS/cesium, pull requests merged in 2023-05, with the labels that each got.

#11277 Fix docstring in `Entity`
  packages/engine/Source/DataSources/Entity.js
Labels: category - doc

#11308 Fix misleading warnings for OES_standard_derivatives
  packages/engine/Source/Renderer/demodernizeShader.js
  packages/engine/Source/Scene/Cesium3DTileBatchTable.js
  packages/engine/Source/Shaders/BillboardCollectionFS.glsl
  packages/engine/Source/Shaders/Builtin/Functions/writeLogDepth.glsl
  packages/engine/Source/Shaders/Materials/ElevationContourMaterial.glsl
  packages/engine/Source/Shaders/Materials/GridMaterial.glsl
  packages/engine/Source/Shaders/Materials/PolylineArrowMaterial.glsl
  packages/engine/Source/Shaders/Model/ModelFS.glsl
Labels: modernization, category - custom shaders

#11311 Terrain & imagery provider ready deprecation fixes
  CHANGES.md
  packages/engine/Source/Core/ArcGISTiledElevationTerrainProvider.js
  packages/engine/Source/Core/CesiumTerrainProvider.js
  packages/engine/Source/Core/CustomHeightmapTerrainProvider.js
  packages/engine/Source/Core/EllipsoidTerrainProvider.js
  packages/engine/Source/Core/GoogleEarthEnterpriseMetadata.js
  packages/engine/Source/Core/GoogleEarthEnterpriseTerrainProvider.js
  packages/engine/Source/Core/VRTheWorldTerrainProvider.js
  packages/engine/Source/Core/createWorldTerrain.js
  packages/engine/Source/Core/sampleTerrain.js
  packages/engine/Source/Core/sampleTerrainMostDetailed.js
  packages/engine/Source/DataSources/ModelVisualizer.js
  packages/engine/Source/Scene/ArcGisMapServerImageryProvider.js
  packages/engine/Source/Scene/BingMapsImageryProvider.js
  packages/engine/Source/Scene/Globe.js
  packages/engine/Source/Scene/GlobeSurfaceTile.js
  packages/engine/Source/Scene/GlobeSurfaceTileProvider.js
  packages/engine/Source/Scene/GoogleEarthEnterpriseImageryProvider.js
  packages/engine/Source/Scene/GoogleEarthEnterpriseMapsProvider.js
  packages/engine/Source/Scene/GridImageryProvider.js
  packages/engine/Source/Scene/Imagery.js
  packages/engine/Source/Scene/ImageryLayer.js
  packages/engine/Source/Scene/IonImageryProvider.js
  packages/engine/Source/Scene/MapboxImageryProvider.js
  packages/engine/Source/Scene/MapboxStyleImageryProvider.js
  packages/engine/Source/Scene/SingleTileImageryProvider.js
  packages/engine/Source/Scene/TileCoordinatesImageryProvider.js
  packages/engine/Source/Scene/TileMapServiceImageryProvider.js
  packages/engine/Source/Scene/UrlTemplateImageryProvider.js
  packages/engine/Source/Scene/WebMapServiceImageryProvider.js
  packages/engine/Source/Scene/WebMapTileServiceImageryProvider.js
  packages/engine/Source/Scene/computeFlyToLocationForRectangle.js
  packages/engine/Source/Scene/createOsmBuildings.js
  packages/engine/Source/Scene/createWorldImagery.js
  packages/engine/Source/Widget/CesiumWidget.js
  packages/engine/Specs/Scene/ImageryLayerCollectionSpec.js
  packages/widgets/Source/Viewer/Viewer.js
  packages/widgets/Specs/BaseLayerPicker/BaseLayerPickerViewModelSpec.js
  packages/widgets/Specs/Viewer/ViewerSpec.js
Labels: priority - next release

#11319 Fix for zoom on tracked entity
  CHANGES.md
  packages/engine/Source/Scene/ScreenSpaceCameraController.js
  packages/engine/Specs/Scene/ScreenSpaceCameraControllerSpec.js
Labels: priority - next release
