Repository CesiumGS/cesium, pull requests merged in 2024-09, with the labels that each got.

#12170 Added CallbackPositionProperty
  Apps/Sandcastle/gallery/Callback Position Property.html
  Apps/Sandcastle/gallery/Callback Position Property.jpg
  CHANGES.md
  CONTRIBUTORS.md
  packages/engine/Source/DataSources/CallbackPositionProperty.js
  packages/engine/Source/DataSources/PathVisualizer.js
  packages/engine/Source/DataSources/PositionProperty.js
  packages/engine/Specs/DataSources/CallbackPositionPropertySpec.js
  packages/engine/Specs/DataSources/ConstantPositionPropertySpec.js
  packages/engine/Specs/DataSources/PathVisualizerSpec.js
Labels: PR - Changes Requested

#12201 Fix depth sampling for ambient occlusion
  CHANGES.md
  packages/engine/Source/Shaders/PostProcessStages/AmbientOcclusionGenerate.glsl
Labels: category - post-processing, category - lighting, PR - Changes Requested

#12188 Improve documentation and readability in Scene and depth-related code
  packages/engine/Source/Core/Matrix4.js
  packages/engine/Source/Core/Occluder.js
  packages/engine/Source/Core/PerspectiveFrustum.js
  packages/engine/Source/Core/PerspectiveOffCenterFrustum.js
  packages/engine/Source/Renderer/Context.js
  packages/engine/Source/Renderer/DrawCommand.js
  packages/engine/Source/Renderer/Framebuffer.js
  packages/engine/Source/Renderer/FramebufferManager.js
  packages/engine/Source/Renderer/MultisampleFramebuffer.js
  packages/engine/Source/Renderer/UniformState.js
  packages/engine/Source/Scene/Camera.js
  packages/engine/Source/Scene/DerivedCommand.js
  packages/engine/Source/Scene/GlobeDepth.js
  packages/engine/Source/Scene/GlobeTranslucencyState.js
  packages/engine/Source/Scene/OIT.js
  packages/engine/Source/Scene/PickDepth.js
  packages/engine/Source/Scene/Picking.js
  packages/engine/Source/Scene/PostProcessStage.js
  packages/engine/Source/Scene/PostProcessStageCollection.js
  packages/engine/Source/Scene/Scene.js
  packages/engine/Source/Scene/TranslucentTileClassification.js
  packages/engine/Source/Scene/View.js
  packages/engine/Source/Shaders/Builtin/Functions/packDepth.glsl
  packages/engine/Source/Shaders/Builtin/Functions/unpackDepth.glsl
  packages/engine/Source/Shaders/Builtin/Functions/windowToEyeCoordinates.glsl
  packages/engine/Source/Shaders/Builtin/Functions/writeLogDepth.glsl
  packages/engine/Source/Shaders/DepthPlaneVS.glsl
  packages/engine/Specs/Scene/GlobeTranslucencyStateSpec.js
  packages/engine/Specs/Scene/SpecularEnvironmentCubeMapSpec.js
  packages/engine/Specs/Scene/TranslucentTileClassificationSpec.js
Labels: cleanup, category - doc

#12212 per naming convention and #4921 this should make this `Rectangle.validate` private.
  CHANGES.md
  CONTRIBUTORS.md
  packages/engine/Source/Core/Rectangle.js
  packages/engine/Source/Core/RectangleGeometry.js
  packages/engine/Source/Core/RectangleOutlineGeometry.js
  packages/engine/Specs/Core/RectangleSpec.js
Labels: PR - Changes Requested

#12204 GPM 1.2 support
  CHANGES.md
  packages/engine/Source/Scene/GltfLoader.js
  packages/engine/Source/Scene/Model/Extensions/Gpm/AnchorPointDirect.js
  packages/engine/Source/Scene/Model/Extensions/Gpm/AnchorPointIndirect.js
  packages/engine/Source/Scene/Model/Extensions/Gpm/CorrelationGroup.js
  packages/engine/Source/Scene/Model/Extensions/Gpm/GltfGpmLoader.js
  packages/engine/Source/Scene/Model/Extensions/Gpm/GltfGpmLocal.js
  packages/engine/Source/Scene/Model/Extensions/Gpm/GltfMeshPrimitiveGpmLoader.js
  packages/engine/Source/Scene/Model/Extensions/Gpm/MeshPrimitiveGpmLocal.js
  packages/engine/Source/Scene/Model/Extensions/Gpm/PpeMetadata.js
  packages/engine/Source/Scene/Model/Extensions/Gpm/PpeSource.js
  packages/engine/Source/Scene/Model/Extensions/Gpm/PpeTexture.js
  packages/engine/Source/Scene/Model/Extensions/Gpm/Spdcf.js
  packages/engine/Source/Scene/Model/Extensions/Gpm/StorageType.js
  packages/engine/Source/Scene/Model/Model.js
  packages/engine/Source/Scene/Model/Model3DTileContent.js
  packages/engine/Source/Scene/ModelComponents.js
  packages/engine/Specs/Scene/Model/Extensions/Gpm/GltfGpmLoaderSpec.js
  packages/engine/Specs/Scene/Model/Extensions/Gpm/GltfMeshPrimitiveGpmLoaderSpec.js
Labels: priority - next release

#12075 Metadata picking preparation
  CHANGES.md
  packages/engine/Source/Renderer/DrawCommand.js
  packages/engine/Source/Scene/DerivedCommand.js
  packages/engine/Source/Scene/FrameState.js
  packages/engine/Source/Scene/MetadataPicking.js
  packages/engine/Source/Scene/Model/MetadataPickingPipelineStage.js
  packages/engine/Source/Scene/Model/ModelDrawCommands.js
  packages/engine/Source/Scene/Model/ModelMatrixUpdateStage.js
  packages/engine/Source/Scene/Model/ModelRuntimePrimitive.js
  packages/engine/Source/Scene/Model/ModelSceneGraph.js
  packages/engine/Source/Scene/Model/PrimitiveRenderResources.js
  packages/engine/Source/Scene/Model/SelectedFeatureIdPipelineStage.js
  packages/engine/Source/Scene/PickFramebuffer.js
  packages/engine/Source/Scene/PickedMetadataInfo.js
  packages/engine/Source/Scene/Picking.js
  packages/engine/Source/Scene/PropertyTextureProperty.js
  packages/engine/Source/Scene/Scene.js
  packages/engine/Source/Scene/getMetadataClassProperty.js
  packages/engine/Source/Shaders/Model/ModelFS.glsl
  packages/engine/Specs/Scene/Model/ModelRuntimePrimitiveSpec.js
  packages/engine/Specs/Scene/SceneSpec.js
Labels: priority - next release

#12224 Fix issue with copying to a texture from a HTMLVideoElement
  CHANGES.md
  packages/engine/Source/Renderer/Texture.js
  packages/engine/Specs/Renderer/TextureSpec.js
Labels: priority - next release
