Repository CesiumGS/cesium, pull requests merged in 2024-06, with the labels that each got.

#12013 Add japan building data sandcastle
  Apps/Sandcastle/gallery/Japan Buildings.html
  Apps/Sandcastle/gallery/Japan Buildings.jpg
Labels: priority - next release

#12015 JP translations
  Apps/Sandcastle/gallery/Japan Buildings.html
Labels: priority - next release

#12043 Fix base color and reflectivity calculations for PBR materials
  CHANGES.md
  packages/engine/Source/Shaders/Builtin/Structs/modelMaterial.glsl
  packages/engine/Source/Shaders/Model/MaterialStageFS.glsl
Labels: priority - next release, category - model

#12054 Fix uniform name for scaling clearcoat normals
  packages/engine/Source/Shaders/Model/MaterialStageFS.glsl
Labels: priority - next release, test failure
