Repository CesiumGS/cesium, pull requests merged in 2024-11, with the labels that each got.

#12253 feat: Introduce `SampledProperty` new function `getSample`
  CHANGES.md
  packages/engine/Source/DataSources/SampledProperty.js
  packages/engine/Specs/DataSources/SampledPropertySpec.js
Labels: PR - Changes Requested

#12237 Proper handling of offset and scale in metadata picking
  CHANGES.md
  packages/engine/Source/Scene/DerivedCommand.js
  packages/engine/Source/Scene/MetadataClassProperty.js
  packages/engine/Source/Scene/MetadataPicking.js
  packages/engine/Source/Scene/MetadataType.js
  packages/engine/Source/Scene/Model/Extensions/Gpm/GltfMeshPrimitiveGpmLoader.js
  packages/engine/Source/Scene/PickedMetadataInfo.js
  packages/engine/Source/Scene/Picking.js
  packages/engine/Source/Scene/PropertyAttributeProperty.js
  packages/engine/Source/Scene/PropertyTextureProperty.js
  packages/engine/Source/Scene/Scene.js
  packages/engine/Source/Scene/getMetadataProperty.js
  packages/engine/Specs/Scene/MetadataPickingSpec.js
  packages/engine/Specs/Scene/SceneSpec.js
Labels: priority - next release

#12299 Add option to select which geocoder is used
  Apps/Sandcastle/gallery/3D Tiles Vertical Exaggeration.html
  Apps/Sandcastle/gallery/AEC Clipping.html
  Apps/Sandcastle/gallery/Bing Maps Labels Only.html
  Apps/Sandcastle/gallery/Clamp Entities to Ground.html
  Apps/Sandcastle/gallery/Clipping Regions.html
  Apps/Sandcastle/gallery/Globe Interior.html
  Apps/Sandcastle/gallery/Google Photorealistic 3D Tiles with Building Insert.html
  Apps/Sandcastle/gallery/Google Photorealistic 3D Tiles.html
  Apps/Sandcastle/gallery/Imagery Color To Alpha.html
  Apps/Sandcastle/gallery/Imagery Layers Manipulation.html
  Apps/Sandcastle/gallery/Imagery Layers Split.html
  Apps/Sandcastle/gallery/development/3D Tiles Picking.html
  CHANGES.md
  packages/engine/Source/Core/BingMapsGeocoderService.js
  packages/engine/Source/Core/GoogleGeocoderService.js
  packages/engine/Source/Core/IonGeocodeProviderType.js
  packages/engine/Source/Core/IonGeocoderService.js
  packages/engine/Source/Scene/createGooglePhotorealistic3DTileset.js
  packages/engine/Specs/Core/GoogleGeocoderServicesSpec.js
  packages/engine/Specs/Core/IonGeocoderServiceSpec.js
  packages/widgets/Source/Viewer/Viewer.js
  packages/widgets/Specs/Viewer/ViewerSpec.js
Labels: priority - next release

#12232 GPM sandcastle
  Apps/Sandcastle/gallery/3D Tiles NGA GPM Visualization.html
  Apps/Sandcastle/gallery/3D Tiles NGA GPM Visualization.jpg
Labels: priority - next release

#12326 Add AEC design sandcastle examples
  Apps/Sandcastle/gallery/AEC Architectural Design.html
  Apps/Sandcastle/gallery/AEC Architectural Design.jpg
  Apps/Sandcastle/gallery/AEC Isolate by Category.html
  Apps/Sandcastle/gallery/AEC Isolate by Category.jpg
  Apps/Sandcastle/gallery/AEC Metadata Styling.html
  Apps/Sandcastle/gallery/AEC Metadata Styling.jpg
  CONTRIBUTORS.md
Labels: priority - next release

#12336 Update npm packages
  package.json
Labels: priority - next release

#12320 Throttle total resources used for environment maps
  CHANGES.md
  packages/engine/Source/Renderer/ContextLimits.js
  packages/engine/Source/Scene/DynamicEnvironmentMapManager.js
  packages/engine/Specs/Scene/DynamicEnvironmentMapManagerSpec.js
Labels: priority - next release

#12339 Remove `Rectangle.validate`
  CHANGES.md
  packages/engine/Source/Core/Rectangle.js
Labels: priority - next release, remove in 1.124

#12331 Draft for handling shared textures in statistics
  CHANGES.md
  Specs/Data/Cesium3DTiles/Tilesets/TilesetWithSharedTextures/plane-0.glb
  Specs/Data/Cesium3DTiles/Tilesets/TilesetWithSharedTextures/plane-1.glb
  Specs/Data/Cesium3DTiles/Tilesets/TilesetWithSharedTextures/plane-2.glb
  Specs/Data/Cesium3DTiles/Tilesets/TilesetWithSharedTextures/plane-3.glb
  Specs/Data/Cesium3DTiles/Tilesets/TilesetWithSharedTextures/texture0.png
  Specs/Data/Cesium3DTiles/Tilesets/TilesetWithSharedTextures/texture1.png
  Specs/Data/Cesium3DTiles/Tilesets/TilesetWithSharedTextures/tileset.json
  packages/engine/Source/Renderer/Texture.js
  packages/engine/Source/Scene/Cesium3DTilesetStatistics.js
  packages/engine/Source/Scene/GltfTextureLoader.js
  packages/engine/Source/Scene/Model/Model3DTileContent.js
  packages/engine/Source/Scene/Model/ModelStatistics.js
  packages/engine/Specs/Scene/Cesium3DTilesetSpec.js
  packages/engine/Specs/Scene/Model/ModelStatisticsSpec.js
Labels: priority - next release
