Repository CesiumGS/cesium, pull requests merged in 2025-03, with the labels that each got.

#12497 upgrade packages - March 2025 release
  eslint.config.js
  package.json
  packages/engine/package.json
Labels: PR - Changes Requested

#12467 Fixes issue #12465 (Entity Tracking broken)
  CHANGES.md
  packages/engine/Source/Widget/CesiumWidget.js
  packages/engine/Specs/DataSources/EntityViewSpec.js
Labels: priority - next release

#12529 Fix type definitions in terrain providers
  packages/engine/Source/Core/ArcGISTiledElevationTerrainProvider.js
  packages/engine/Source/Core/CesiumTerrainProvider.js
  packages/engine/Source/Core/EllipsoidTerrainProvider.js
  packages/engine/Source/Core/GoogleEarthEnterpriseTerrainData.js
  packages/engine/Source/Core/GoogleEarthEnterpriseTerrainProvider.js
  packages/engine/Source/Core/HeightmapTerrainData.js
  packages/engine/Source/Core/QuantizedMeshTerrainData.js
  packages/engine/Source/Core/TerrainData.js
  packages/engine/Source/Core/TerrainProvider.js
  packages/engine/Source/Core/VRTheWorldTerrainProvider.js
  packages/engine/Specs/Core/QuantizedMeshTerrainDataSpec.js
Labels: cleanup, category - doc, theme - 3D Tiles as Terrain
