Repository CesiumGS/cesium, pull requests merged in 2025-07, with the labels that each got.

#12681 Fix step size for cylinder voxels
  Apps/Sandcastle/gallery/Voxel Picking.html
  CHANGES.md
  packages/engine/Source/Shaders/Voxels/convertUvToCylinder.glsl
Labels: priority - next release, category - voxels

#12704 Add hack to avoid Firefox styling bug
  Apps/Sandcastle/CesiumSandcastle.js
Labels: priority - next release

#12706 Update with modelMatrix and correctly handle rotation
  CHANGES.md
  packages/engine/Source/Scene/GaussianSplat3DTileContent.js
  packages/engine/Source/Scene/GaussianSplatPrimitive.js
Labels: priority - next release

#12710 Fix Terrain Classification Sandcastle
  Apps/Sandcastle/gallery/3D Tiles Terrain Classification.html
Labels: priority - next release

#12757 Update version info from prerelease
  ThirdParty.json
  package.json
  packages/engine/package.json
  packages/widgets/package.json
Labels: priority - next release

#12349 Fixed Matrix Multiplication Shaders
  CHANGES.md
  CONTRIBUTORS.md
  packages/engine/Source/Shaders/Builtin/Functions/modelToWindowCoordinates.glsl
  packages/engine/Source/Shaders/EllipsoidVS.glsl
  packages/engine/Source/Shaders/GlobeVS.glsl
  packages/engine/Source/Shaders/SkyAtmosphereVS.glsl
  packages/engine/Specs/Scene/MultifrustumSpec.js
Labels: PR - Changes Requested

#12784 Update npm packages
  CHANGES.md
  package.json
  packages/engine/package.json
Labels: priority - next release

#12783 updated spz-loader to 0.3.0 for SPZ 2.0.0 support
  CHANGES.md
  packages/engine/Source/Scene/GltfSpzLoader.js
  packages/engine/Source/Scene/PrimitiveLoadPlan.js
  packages/engine/package.json
Labels: priority - next release

#12778 Add support for optional changesets when loading iModels
  Apps/Sandcastle/gallery/Drape Imagery on 3D Tiles.html
  Apps/Sandcastle/gallery/iModel Mesh Export Service.html
  Apps/Sandcastle/gallery/iTwin Feature Service.html
  CHANGES.md
  packages/engine/Source/Core/ITwinPlatform.js
  packages/engine/Source/Scene/ITwinData.js
  packages/engine/Specs/Core/ITwinPlatformSpec.js
  packages/engine/Specs/Scene/ITwinDataSpec.js
Labels: priority - next release
